spring:
  application:
    name: complaint
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME:}:${MONGODB_PASSWORD:}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:complaints}?authSource=${MONGODB_AUTH_DATABASE:admin}
  webflux:
    base-path: /complaint

application:
  geolocation:
    base-url: http://ip-api.com
    retry:
      max-attempts: 3
      backoff-ms: 1000

logging:
  level:
    com.empik.complaint: INFO